### ISSUE TITLE
Button label / crash

### ISSUE THREAD

**Issue by davidraythompson** [openspectra/openspectra#28]
The button label "open" is a bit ambiguous - it's the first thing one sees when launching the application, but rather than opening a file, clicking on it causes a crash :)  Maybe "show image" would be a more accurate label? It would also be nice to not crash when attempting to view the image without an open file.

**Comment by jconti13** [comment]
Fixed in the master branch.  
Changed the button label as suggested.  
Fixed crashing problem by making sure the button is disabled until there is a valid selection of bands for rgb or a single band selected for grey scale.
