### ISSUE TITLE
time() throws errors

### ISSUE THREAD

**Issue by davidraythompson** [openspectra/openspectra#3]
I get errors like the following, running on a mac - I think it happens with a button press in the active image.  

Traceback (most recent call last):
  File "/Users/drt/src/openspectra/openspectra/ui/imagedisplay.py", line 541, in mousePressEvent
    self.__select_pixel(adjust_mouse_event)
  File "/Users/drt/src/openspectra/openspectra/ui/imagedisplay.py", line 736, in __select_pixel
    adjusted_mouse_event.mouse_event().x(), adjusted_mouse_event.mouse_event().y()))
  File "/Users/drt/src/openspectra/openspectra/ui/imagedisplay.py", line 277, in get_points
    start_time = time.perf_counter_ns()

**Comment by davidraythompson** [comment]
Sorry, my copy and paste cut off the actual nature of the exception, which is 

AttributeError: module 'time' has no attribute ‘perf_counter_ns'



AttributeError: module 'time' has no attribute 'perf_counter_ns'
Abort trap: 6

Could this be a versioning issue?

**Comment by davidraythompson** [comment]
FYI It looks like Python 3.6.8 doesn't work :)
Installing Python 3.7 solved the issue.

**Comment by jconti13** [comment]
Yup you're exactly right.  It was just some code to time how long the operation was taking so I removed it.  pull from master now and you'll get the fix.  Please close the issue if you verify the fix works for you.  Thanks!

**Comment by jconti13** [comment]
Oh ok didn't see u already closed.  Probably a good idea to leave that out of there anyway in case some of the workshop folks don't have the very latest python

**Comment by davidraythompson** [comment]
Thanks for the fast action on this - I should have read the  installation dependencies more closely!
